import base from "@bookflow/config/eslint";

// database.types.ts is generated by `supabase gen types`; CI diffs it against fresh output, so it stays untouched.
export default [...base, { ignores: ["src/database.types.ts"] }];
