#!/usr/bin/env node
//
// Writes packages/contracts/openapi.json from the running app's Zod route
// schemas (ADR-014, ADR-025).
//
// Builds the Fastify instance in-process and asks @fastify/swagger for the
// document. Nothing here describes the API — it reads the same declarations
// the runtime validates against, which is the point.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { buildApp } from '../apps/api/src/app.ts';

const OUTPUT = resolve('packages/contracts/openapi.json');

// The spec is a build product, not a runtime. It needs a valid config object,
// not a real environment: no port is bound and no database is touched.
const config = {
  APP_ENV: 'local',
  PORT: 3000,
  HOST: '127.0.0.1',
  DATABASE_URL: 'postgresql://unused:unused@127.0.0.1:1/unused',
  SUPABASE_URL: 'http://127.0.0.1:54321',
  SUPABASE_JWT_AUDIENCE: 'authenticated',
};

// No database and no auth server are reached: `app.ready()` builds the route
// table and the JWKS is fetched lazily, on the first request, which never
// happens here.
const app = await buildApp(config, {
  db: () => {
    throw new Error('the spec generator never executes a query');
  },
});
await app.ready();

const document = app.swagger();

// JSON has no comment syntax, so the "do not edit" notice is an OpenAPI
// extension key instead, placed first so it is the first thing anyone opening
// the file reads. `x-` members are valid anywhere in an OpenAPI document and
// are ignored by every generator.
const annotated = {
  'x-generated': [
    'DO NOT EDIT THIS FILE BY HAND.',
    'Generated from the Zod route schemas in apps/api by `npm run contracts:generate`.',
    'ADR-014: the spec is generated from code, never hand-written.',
    'ADR-025: CI regenerates it and fails on any diff, so a hand edit is a build failure.',
  ].join(' '),
  ...document,
};

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, `${JSON.stringify(annotated, null, 2)}\n`, 'utf8');

await app.close();

console.log(`openapi: wrote ${OUTPUT}`);
